export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/auth/login",
    REFRESH_TOKEN: "/api/auth/refresh-token",
    LOGOUT: "/api/auth/logout",
  },
  USER: {
    PROFILE: "/api/user/profile",
    MY_DETAILS: "https://gymmanagement-backend-1wvo.onrender.com/api/user/my-details",
    UPDATE: "/api/user/update",
    DETAIL: (id: string) => `/api/user/${id}`,
    RESET_PASSWORD: (id: string) => `/api/user/${id}/reset-password`,
    DOWNLOAD_IDCARD: (id: string) => `/api/user/${id}/download-idcard`,
  },
  ADMIN: {
    USERS: "/api/admin/user_roles/users",
    TRAINER_LIST: "/api/admin/user_roles/trainer_list",
    GET_USERS_DROPDOWN: "/api/admin/user_roles/get-users-dropdown",
    USER_CREATE: "/api/admin/user_roles/users/create",
    USER_EDIT: (id: string) => `/api/admin/user_roles/users/${id}/edit`,
    USER_UPLOAD: (id: string) => `/api/admin/user_roles/users/${id}/upload_file`,
    USER_DOC_DELETE: (id: string) => `/api/admin/user_roles/users/${id}/docs`,
    USER_STATUS: (id: string) => `/api/admin/user_roles/users/${id}/status`,
    USER_DELETE: (id: string) => `/api/admin/user_roles/users/${id}`,
    ROLES: "/api/admin/user_roles/roles",
    PLANS: "/api/admin/subscription/subscription-plans",
    PLAN_DETAIL: (id: string) => `/api/admin/subscription/subscription-plans/${id}`,
    SUBSCRIPTION_HISTORY: "/api/admin/subscription/subscription-history",
    SUBSCRIPTION_CREATE: "/api/admin/user_roles/subscription-plan-create",
    PRODUCTS: "/api/admin/product/",
    PRODUCT_DETAIL: (id: string) => `/api/admin/product/${id}`,
    PAYMENTS: "/api/admin/payment/",
    PAYMENT_DETAIL: (id: string) => `/api/admin/payment/${id}`,
    SYNC_SUBSCRIPTIONS: "/api/admin/user_roles/sync-users-subscription-plans",
    ATTENDANCE: "/api/admin/attendance/",
    ATTENDANCE_STATS: "/api/admin/attendance/attendance-stats",
    ATTENDANCE_USER: (userId: string) => `/api/admin/attendance/${userId}`,
    ATTENDANCE_DETAIL: (id: string) => `/api/admin/attendance/${id}`,
    ATTENDANCE_EDIT: (attendanceId: string, userId: string) => `/api/admin/attendance/${attendanceId}/user/${userId}`,
    INQUIRIES_CONTACT: "/api/admin/inquiries/contact-page",
    INQUIRIES_PRODUCT_ORDER: "/api/admin/inquiries/product-orders",
    INQUIRIES_SUBSCRIPTION: "/api/admin/inquiries/subscriptions",
    INQUIRIES_EXPIRING: "/api/admin/inquiries/expiring-members",
    REVENUE_STATS: "/api/admin/revenue/stats",
    REVENUE_PAYMENTS: "/api/admin/revenue/payments",
    REVENUE_PAYMENTS_SUBSCRIPTIONS: "/api/admin/revenue/payments/subscriptions",
    REVENUE_PAYMENTS_PRODUCTS: "/api/admin/revenue/payments/products",
    REVENUE_CONTACT_INQUIRIES: "/api/admin/revenue/contact-inquiries",
    DASHBOARD_STATS: "/api/admin/dashboard/stats",
    DASHBOARD_RECENT_INQUIRIES: "/api/admin/dashboard/recent-inquiries",
    DASHBOARD_RECENT_PAYMENTS: "/api/admin/dashboard/recent-payments",
    DASHBOARD_RECENT_SUBSCRIPTIONS: "/api/admin/dashboard/recent-subscription-history",
    DASHBOARD_RECENT_PRODUCTS: "/api/admin/dashboard/recent-product-purchases",
    DASHBOARD_ATTENDANCE: "/api/admin/dashboard/attendance-count",
    DASHBOARD_MONTHLY_REVENUE: "/api/admin/dashboard/monthly-revenue",
    APP_CONFIG: "/api/admin/app-config/",
    APP_CONFIG_UPLOAD: "/api/admin/app-config/upload-app-config-files",
    LOCATION: "/api/admin/location/",
    LOCATION_DETAIL: (id: string) => `/api/admin/location/${id}`,
  },
  APP: {
    INQUIRIES_CONTACT: "/api/app/inquiries/contact-page",
    INQUIRIES_PRODUCT_ORDER: "/api/app/inquiries/product-orders",
    INQUIRIES_SUBSCRIPTION: "/api/app/inquiries/subscriptions",
    INQUIRIES_EXPIRING: "/api/app/inquiries/expiring-members",
    PRODUCTS: "/api/app/product/",
    PAYMENTS: (userId: string) => `/api/app/payment/${userId}`,
    SUBSCRIPTION_PLANS: "/api/app/subscription/subscription-plans",
    CURRENT_SUBSCRIPTION: (userId: string) => `/api/app/subscription/current-subscription/${userId}`,
    SUBSCRIPTION_HISTORY: (userId: string) => `/api/app/subscription/subscription-history/${userId}`,
    ATTENDANCE_STATS: (userId: string) => `/api/app/attendance/attendance-stats/${userId}`,
    ATTENDANCE: (userId: string) => `/api/app/attendance/${userId}`,
  }
} as const;

export type ApiEndpoint = typeof API_ENDPOINTS;
